version: '3'
services:
  keosd:
    build:
      context: ./
      dockerfile: eosdev_Dockerfile
    command: keosd --http-server-address=0.0.0.0:8888 --data-dir=/app/eosio/data --http-validate-host=false
    container_name: taikai_keosd
    hostname: keosd
    environment:
      - CONTRACT_PKEY
    ports:
    - "8899:8888"
    networks:
      - eosio
  nodeos:
    build:
      context: ./
      dockerfile: eosdev_Dockerfile
    container_name: taikai_nodeos
    hostname: nodeos
    environment:
      - CONTRACT_PKEY
    ports:
    - "8888:8888"
    depends_on:
      - keosd
    networks:
      - eosio
networks:
  eosio:
    driver: "bridge"